### PR TITLE
Add head checkout in action

### PR DESCRIPTION
**Pull request by sk8higher**
I'm not sure how can I test it on my local machine so we don't have a bunch of PRs, tried `act` but it fails because I don't have github token locally. I think I should do something with checkout action so it sees the repo.

### CODE REVIEW

**Comment by sk8higher** [comment]
Or maybe override default `rake release` task, but I'm not sure how to do this https://stackoverflow.com/questions/20824049/rake-release-fail-using-gem-bundler

**Comment by sergio-fry** [comment]
@sk8higher is it possible to fork, register your own gem at rubygems and try to get success in your repo?

**Comment by sk8higher** [comment]
> @sk8higher is it possible to fork, register your own gem at rubygems and try to get success in your repo?

i'll try

**Comment by sk8higher** [comment]
I've tried this action, it works but I needed to configure MFA with 'UI and gem signin' level, also I've added rubygems api key to repository secrets.

**Review by sergio-fry — APPROVED** [review]

**Pull request merged**
